---
title: "Atividade 09"
author: "Adriano Araújo"
date: "October 17, 2018"
output:
  html_document: default
  pdf_document: default
---

```{r}
require(pacman)
require(tidyverse)

capes <- read_csv2("/home/adriano/Documents/MD/CLSS-01/capes.csv")
capes <- select(capes,-c("AN_BASE",
                       "CD_PROGRAMA",
                       "NM_ENTIDADE_ENSINO",
                       "ID_ADD_PRODUCAO_INTELECTUAL",
                       "ID_PRODUCAO_INTELECTUAL",
                       "ID_SUBTIPO_PRODUCAO",
                       "ID_AREA_CONCENTRACAO",
                       "ID_LINHA_PESQUISA",
                       "ID_PROJETO",
                       "DH_INICIO_AREA_CONC",
                       "DH_FIM_AREA_CONC",
                       "DH_INICIO_LINHA",
                       "DH_FIM_LINHA",
                       "DT_TITULACAO",
                       "DS_KEYWORD",
                       "ID_TP_EXPECTATIVA_ATUACAO",
                       "ID_PESSOA_DISCENTE",
                       "DT_MATRICULA",
                       "ID_GRAU_ACADEMICO",
                       "DS_CATEGORIA_ORIENTADOR",
                       "NM_REGIAO",
                       "NM_UF_IES",
                       "CD_GRANDE_AREA_CONHECIMENTO",
                       "CD_AREA_CONHECIMENTO",
                       "CD_SUBAREA_CONHECIMENTO",
                       "CD_ESPECIALIDADE",
                       "NM_ESPECIALIDADE",
                       "DS_EMAIL_DISCENTE",
                       "NR_VOLUME",
                       "DS_RESUMO",
                       "DS_URL_TEXTO_COMPLETO",
                       "ID_PESSOA_ORIENTADOR",
                       
                       "NM_PROGRAMA",
                       "NM_PRODUCAO",
                       "NM_SUBTIPO_PRODUCAO",
                       "NM_PROJETO",
                       "IN_TRABALHO_MESMA_AREA",
                       "NM_TP_VINCULO",
                       "IN_ORIENT_PARTICIPOU_BANCA",
                       "DS_BIBLIOTECA_DEPOSITARIA",
                       "NM_EXPECTATIVA_ATUACAO",
                       "NM_DISCENTE",
                       "NM_GRAU_ACADEMICO",
                       "NM_CATEGORIA_DOCENTE",
                       "SG_UF_IES",
                       "NM_AREA_AVALIACAO",
                       "NR_PAGINAS",
                       "NM_IDIOMA",
                       "NM_DISCENTE",
                       "NM_PROJETO",
                       
                       "NM_AREA_CONCENTRACAO",
                       "NM_LINHA_PESQUISA",
                       "NM_SUBAREA_CONHECIMENTO",
                       "DS_PALAVRA_CHAVE",
                       
                       "NM_ORIENTADOR",
                       "NM_AREA_CONHECIMENTO"))

glimpse(capes)

capes$SG_ENTIDADE_ENSINO <- as.factor(capes$SG_ENTIDADE_ENSINO)
capes$DS_ABSTRACT <- as.character(capes$DS_ABSTRACT)
capes$NM_GRANDE_AREA_CONHECIMENTO <- as.factor(capes$NM_GRANDE_AREA_CONHECIMENTO)

capes$DS_ABSTRACT <- tolower(capes$DS_ABSTRACT)
capes <- filter(capes, SG_ENTIDADE_ENSINO == "UFU")
capes$ID <- seq.int(nrow(capes))
capes$SG_ENTIDADE_ENSINO <- NULL

glimpse(capes)

p_load(readtext, tidyverse, quanteda)

corpora <- corpus(capes,docid_field = "ID", text_field = "DS_ABSTRACT")

words <- tokens(corpora,remove_punct = TRUE,remove_numbers = TRUE)
words <- tokens_remove(words,stopwords("en"))

indice <- dfm(words) %>% dfm_trim(max_docfreq = 239,max_termfreq = 37)
textstat_frequency(indice)

area <- corpora$documents$NM_GRANDE_AREA_CONHECIMENTO[ntoken(indice)>0]
indice <- indice[ntoken(indice)>0,]

indiceTFIDF <- dfm_tfidf(indice,scheme_df = "count",scheme_tf = "boolean")

matriz <- as.matrix(indiceTFIDF)
cat("Dimensões número docs X número de palavras:", dim(matriz),"\n")
cat("Exemplos de pesos de documentos:\n")
print(matriz[1,1:20])
```

```{r}
p_load(caret)

inTraining <- createDataPartition(area,p=.05)$Resample1
indiceTFIDF <- dfm_tfidf(indice[inTraining],scheme_df = "count",scheme_tf = "boolean")
matriz <- as.matrix(indiceTFIDF)

fitControl <- trainControl(method = "repeatedcv",
                           number = 2,
                           repeats = 10)


set.seed(666)
gbmFit1 <- train(area[inTraining] ~ ., data = matriz, 
                 method = "gbm", 
                 trControl = fitControl,
                 verbose = FALSE)
```

