---
title: "Exposição simples de dados"
author: "Bernardo"
date: "28 de agosto de 2018"
output:
  html_document: default
  pdf_document: default
---

#Relação da Jornada de trabalho em horas por semana:
#A média da jornada de trabalho é 40 horas por semana.
```{r}

cadastro <- read.csv2("/home/gudnunes/Área de Trabalho/Mineração de dados/MD2018/dados/cadastrocivil.csv")
horario = rep(0, nrow(cadastro))
i = 1
for (aux in as.character(cadastro$JORNADA_DE_TRABALHO)) {
  
  if(aux == "12 HORAS SEMANAIS")
    horario[i]<-12
  
  if(aux == "18 HORAS SEMANAIS")
    horario[i]<-18
  
  if(aux == "20 HORAS SEMANAIS")
    horario[i]<-20
  
  if(aux == "22 H SEMANAIS JUD.")
    horario[i]<-22
  
  if(aux == "24 HORAS SEMANAIS")
    horario[i]<-24
  
  if(aux == "25 HORAS SEMANAIS")
    horario[i]<-25
  
  if(aux == "30 HORAS SEMANAIS")
    horario[i]<-30
  
  if(aux == "32,5 HORAS SEMANAIS")
    horario[i]<-32
  
  if(aux == "36 HORAS SEMANAIS")
    horario[i]<-36
  
  if(aux == "40 HORAS SEMANAIS")
    horario[i]<-40
  
  if(aux == "44 HORAS SEMANAIS")
    horario[i]<-44
  
  if(aux == "60 HORAS SEMANAIS")
    horario[i]<-60
  
  if(aux == "66 HORAS SEMANAIS")
    horario[i]<-66
  
  i = i + 1
  
}

boxplot(horario, horizontal = T)

```



#Quantidade de funcionários ingressantes em cada data:
```{r}
summary(cadastro$DATA_INGRESSO_ORGAO)
```



